let data={
"Madhya Pradesh":{
    "Indore":{
      25:{
                'Soybean':{
                    'min':1750,
                    "max":2950,
                    'avg':1950,
                    },
                'Wheat':{
                    'min':1700,
                    "max":2900,
                    'avg':1900,
                    },
                'Rice':{
                    'min':1730,
                    "max":2990,
                    'avg':1900,
                    },
                'Gram':{
                    'min':1750,
                    "max":1950,
                    'avg':1800,
                    },
            },
            
      24:{
                'Soybean':{
                    'min':1450,
                    "max":2150,
                    'avg':1650,
                    },
                'Wheat':{
                    'min':1100,
                    "max":1800,
                    'avg':1600,
                    },
                'Rice':{
                    'min':1730,
                    "max":1990,
                    'avg':1800,
                    },
                'Gram':{
                    'min':1750,
                    "max":1950,
                    'avg':1800,
                    },
                },
      23:{
                'Soybean':{
                    'min':1750,
                    "max":2150,
                    'avg':1950,
                    },
                'Wheat':{
                    'min':1700,
                    "max":2500,
                    'avg':1900,
                    },
                'Rice':{
                    'min':1730,
                    "max":2390,
                    'avg':1900,
                    },
                'Gram':{
                    'min':1750,
                    "max":1950,
                    'avg':1800,
                    },
            },
      22:{
                'Soybean':{
                    'min':1650,
                    "max":2570,
                    'avg':1900,
                    },
                'Wheat':{
                    'min':1240,
                    "max":1640,
                    'avg':1400,
                    },
                'Rice':{
                    'min':1330,
                    "max":1890,
                    'avg':1500,
                    },
                'Gram':{
                    'min':1750,
                    "max":1950,
                    'avg':1800,
                    },
            },
        
      21:{
                'Soybean':{
                    'min':1450,
                    "max":1850,
                    'avg':1650,
                    },
                'Wheat':{
                    'min':1800,
                    "max":2000,
                    'avg':1900,
                    },
                'Rice':{
                    'min':1730,
                    "max":2920,
                    'avg':1900,
                    },
                'Gram':{
                    'min':1600,
                    "max":1950,
                    'avg':1700,
                    },
            },
        
      20:{
                'Soybean':{
                    'min':1650,
                    "max":1850,
                    'avg':1750,
                    },
                'Wheat':{
                    'min':1580,
                    "max":2920,
                    'avg':1910,
                    },
                'Rice':{
                    'min':1710,
                    "max":2900,
                    'avg':1950,
                    },
                'Gram':{
                    'min':1750,
                    "max":1900,
                    'avg':1800,
                    },
            },
        },
    
    "Mandla":{
        25:{
                  'Soybean':{
                      'min':1750,
                      "max":2950,
                      'avg':1950,
                      },
                  'Wheat':{
                      'min':1700,
                      "max":2900,
                      'avg':1900,
                      },
                  'Rice':{
                      'min':1730,
                      "max":2990,
                      'avg':1900,
                      },
                  'Gram':{
                      'min':1750,
                      "max":1950,
                      'avg':1800,
                      },
              },
              
        24:{
                  'Soybean':{
                      'min':1450,
                      "max":2150,
                      'avg':1650,
                      },
                  'Wheat':{
                      'min':1100,
                      "max":1800,
                      'avg':1600,
                      },
                  'Rice':{
                      'min':1730,
                      "max":1990,
                      'avg':1800,
                      },
                  'Gram':{
                      'min':1750,
                      "max":1950,
                      'avg':1800,
                      },
                  },
        23:{
                  'Soybean':{
                      'min':1750,
                      "max":2150,
                      'avg':1950,
                      },
                  'Wheat':{
                      'min':1700,
                      "max":2500,
                      'avg':1900,
                      },
                  'Rice':{
                      'min':1730,
                      "max":2390,
                      'avg':1900,
                      },
                  'Gram':{
                      'min':1750,
                      "max":1950,
                      'avg':1800,
                      },
              },
        22:{
                  'Soybean':{
                      'min':1650,
                      "max":2570,
                      'avg':1900,
                      },
                  'Wheat':{
                      'min':1240,
                      "max":1640,
                      'avg':1400,
                      },
                  'Rice':{
                      'min':1330,
                      "max":1890,
                      'avg':1500,
                      },
                  'Gram':{
                      'min':1750,
                      "max":1950,
                      'avg':1800,
                      },
              },
          
        21:{
                  'Soybean':{
                      'min':1450,
                      "max":1850,
                      'avg':1650,
                      },
                  'Wheat':{
                      'min':1800,
                      "max":2000,
                      'avg':1900,
                      },
                  'Rice':{
                      'min':1730,
                      "max":2920,
                      'avg':1900,
                      },
                  'Gram':{
                      'min':1600,
                      "max":1950,
                      'avg':1700,
                      },
              },
          
        20:{
                  'Soybean':{
                      'min':1650,
                      "max":1850,
                      'avg':1750,
                      },
                  'Wheat':{
                      'min':1580,
                      "max":2920,
                      'avg':1910,
                      },
                  'Rice':{
                      'min':1710,
                      "max":2900,
                      'avg':1950,
                      },
                  'Gram':{
                      'min':1750,
                      "max":1900,
                      'avg':1800,
                      },
              },
        },
    "Mandsaur":{
        25:{
                    'Soybean':{
                        'min':1750,
                        "max":2950,
                        'avg':1950,
                        },
                    'Wheat':{
                        'min':1700,
                        "max":2900,
                        'avg':1900,
                        },
                    'Rice':{
                        'min':1730,
                        "max":2990,
                        'avg':1900,
                        },
                    'Gram':{
                        'min':1750,
                        "max":1950,
                        'avg':1800,
                        },
                },
                
        24:{
                    'Soybean':{
                        'min':1450,
                        "max":2150,
                        'avg':1650,
                        },
                    'Wheat':{
                        'min':1100,
                        "max":1800,
                        'avg':1600,
                        },
                    'Rice':{
                        'min':1730,
                        "max":1990,
                        'avg':1800,
                        },
                    'Gram':{
                        'min':1750,
                        "max":1950,
                        'avg':1800,
                        },
                    },
        23:{
                    'Soybean':{
                        'min':1750,
                        "max":2150,
                        'avg':1950,
                        },
                    'Wheat':{
                        'min':1700,
                        "max":2500,
                        'avg':1900,
                        },
                    'Rice':{
                        'min':1730,
                        "max":2390,
                        'avg':1900,
                        },
                    'Gram':{
                        'min':1750,
                        "max":1950,
                        'avg':1800,
                        },
                },
        22:{
                    'Soybean':{
                        'min':1650,
                        "max":2570,
                        'avg':1900,
                        },
                    'Wheat':{
                        'min':1240,
                        "max":1640,
                        'avg':1400,
                        },
                    'Rice':{
                        'min':1330,
                        "max":1890,
                        'avg':1500,
                        },
                    'Gram':{
                        'min':1750,
                        "max":1950,
                        'avg':1800,
                        },
                },
            
        21:{
                    'Soybean':{
                        'min':1450,
                        "max":1850,
                        'avg':1650,
                        },
                    'Wheat':{
                        'min':1800,
                        "max":2000,
                        'avg':1900,
                        },
                    'Rice':{
                        'min':1730,
                        "max":2920,
                        'avg':1900,
                        },
                    'Gram':{
                        'min':1600,
                        "max":1950,
                        'avg':1700,
                        },
                },
            
        20:{
                    'Soybean':{
                        'min':1650,
                        "max":1850,
                        'avg':1750,
                        },
                    'Wheat':{
                        'min':1580,
                        "max":2920,
                        'avg':1910,
                        },
                    'Rice':{
                        'min':1710,
                        "max":2900,
                        'avg':1950,
                        },
                    'Gram':{
                        'min':1750,
                        "max":1900,
                        'avg':1800,
                        },
                },
          }
      }
    }